# IFP Edge - Prometheus Configuration
# Scrapes metrics from all IFP services

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'ifp-edge'
    environment: 'production'

# Alertmanager configuration (optional)
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets: ['alertmanager:9093']

# Scrape configurations
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          service: 'prometheus'
          tier: 'monitoring'

  # IFP SAGE Monitoring Agent
  - job_name: 'sage'
    static_configs:
      - targets: ['sage:8091']
        labels:
          service: 'sage'
          tier: 'monitoring'

  # O2 Wallet Service
  - job_name: 'o2-wallet'
    static_configs:
      - targets: ['o2-wallet:8085']
        labels:
          service: 'o2-wallet'
          tier: 'wallet'

  # Demo Application
  - job_name: 'demo-app'
    static_configs:
      - targets: ['demo-app:80']
        labels:
          service: 'demo-app'
          tier: 'demo'

  # Docker containers with auto-discovery
  # Discovers containers with label: ifp.monitor=true
  - job_name: 'docker-services'
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 30s
    relabel_configs:
      # Only scrape containers with ifp.monitor=true label
      - source_labels: [__meta_docker_container_label_ifp_monitor]
        regex: 'true'
        action: keep

      # Extract service name from container label
      - source_labels: [__meta_docker_container_label_ifp_service]
        target_label: service

      # Extract tier from container label
      - source_labels: [__meta_docker_container_label_ifp_tier]
        target_label: tier

      # Use container name if no service label
      - source_labels: [__meta_docker_container_name]
        target_label: container
        regex: '/(.*)'

      # Extract port from container label or use default
      - source_labels: [__meta_docker_container_label_prometheus_port]
        regex: '(\d+)'
        target_label: __address__
        replacement: '$1'

      # Extract metrics path from label or use default
      - source_labels: [__meta_docker_container_label_prometheus_path]
        target_label: __metrics_path__
        regex: '(.+)'

  # Node Exporter (if available)
  # Uncomment if you want host-level metrics
  # - job_name: 'node-exporter'
  #   static_configs:
  #     - targets: ['node-exporter:9100']
  #       labels:
  #         service: 'node-exporter'
  #         tier: 'system'

  # cAdvisor (if available)
  # Uncomment for container-level metrics
  # - job_name: 'cadvisor'
  #   static_configs:
  #     - targets: ['cadvisor:8080']
  #       labels:
  #         service: 'cadvisor'
  #         tier: 'monitoring'
